# /build.yaml
build_from:
  aarch64: "ghcr.io/hassio-addons/base-debian:stable"
  amd64: "ghcr.io/hassio-addons/base-debian:stable"
  armv7: "ghcr.io/hassio-addons/base-debian:stable"
args:
  TEMPIO_VERSION: "2021.09.0"