# build.yaml
build_from:
  aarch64: "ghcr.io/hassio-addons/debian-base:8.1.3"
  amd64: "ghcr.io/hassio-addons/debian-base:8.1.3"
  armv7: "ghcr.io/hassio-addons/debian-base:8.1.3"
args:
  TEMPIO_VERSION: "2024.11.2"