name: "Web Browser (noVNC)"
version: "1.0.8"
slug: "web_browser_novnc"
description: "Web browser accessible through noVNC in Home Assistant dashboard"
url: "https://github.com/BenePhetes/ha-addons-novnc-web-browser"
arch:
  - amd64
startup: application
boot: manual
ports:
  6080/tcp: 6080
webui: "http://[HOST]:[PORT:6080]/vnc.html?autoconnect=true&resize=scale"
ingress: true
panel_icon: mdi:web
panel_title: "Web Browser"
