name: "Web Browser (noVNC)"
version: "1.1.1"
slug: "web_browser_novnc"
description: "Web browser accessible through noVNC in Home Assistant dashboard"
url: "https://github.com/BenePhetes/ha-addons-novnc-web-browser"
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: manual
init: false
ports:
  6080/tcp: 6080
webui: "http://[HOST]:[PORT:6080]/vnc.html?autoconnect=true&resize=scale"
ingress: true
panel_icon: mdi:web
panel_title: "Web Browser"
options:
  resolution: "1920x1080"
  homepage: "https://google.com"
  password: ""
  scaling: "remote"
  compression: 6
  quality: 6
schema:
  resolution: "str"
  homepage: "url"
  password: "str?"
  scaling: "list(off|local|remote)"
  compression: "int(0,9)"
  quality: "int(0,9)"
image: "ghcr.io/{arch}-addon-web-browser-novnc"