# /config.yaml
name: "Web Browser (Xpra)"
version: "1.0.1"
slug: "web-browser-xpra"
description: "High-performance web browser with Xpra"
arch:
  - aarch64
  - amd64
  - armv7
init: false
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:web
options:
  browser: "brave"
  url: "http://homeassistant.local:8123"
schema:
  browser: list(brave|opera)
  url: str