name: "Web Browser (noVNC)"
version: "1.0.4"
slug: "web_browser_novnc"
description: "Simple web browser using noVNC"
url: "https://github.com/BenePhetes/ha-addons-novnc-web-browser"
arch:
  - amd64
startup: application
boot: manual
ports:
  6080/tcp: 6080
webui: "http://[HOST]:[PORT:6080]/vnc.html?autoconnect=true"
ingress: true
panel_icon: mdi:web
panel_title: "Web Browser"
